version: '3'
services:
    back:
        image: networksidea/backend:latest
        container_name: backend
    front:
        image: networksidea/frontend:latest 
        container_name: frontend
        environment: 
            - FRONTEND_PORT=80
    nginx:
        build: ./nginx
        ports: 
            - "80:80"