version: '3'
services:
    db:
      image: mongo
      container_name: db
      ports:
        - "27017:27017"
    back:
        build: .
        container_name: backend
        environment:
          - DB_HOST=db
        depends_on: 
          - db
    front:
        build: ./frontend
        container_name: frontend
        environment: 
          - FRONTEND_PORT=80
    nginx:
        build: ./nginx
        depends_on: 
          - back
          - front
        ports: 
            - "80:80"


