#!/bin/sh

if [ -e frontend ]; then
    git -C ./frontend pull
else 
    git clone git@github.com:Web-networks/frontend.git frontend/
fi
export NODE_ENV=development
docker-compose -f docker-compose-dev.yml up --build --force-recreate -d
node ./tasks/load-fixtures.js
