name: CI

on: push

jobs:
    linter:
        name: Lint checking
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10]
        steps:
        - uses: actions/checkout@v1
        - name: yarn install
          run: yarn

        - name: yarn lint
          run: yarn lint
          
    server-tests:
        name: Server tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10]
        steps:
        - uses: actions/checkout@v1
        - name: yarn install
          run: yarn

        - name: yarn 
          run: yarn test