name: CI

on: push

jobs:
    linter:
        name: Lint checking
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10]
        steps:
        - uses: actions/checkout@v1
        - name: yarn install
          run: yarn

        - name: yarn lint
          run: yarn lint

    building-test:
        name: TS checking
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10]
        steps:
        - uses: actions/checkout@v1
        - name: yarn install
          run: yarn

        - name: yarn tsc --noEmit
          run: yarn tsc --noEmit
          
    server-tests:
        name: Server tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10]
        steps:
        - uses: actions/checkout@v1
        - name: yarn install
          run: yarn

        - name: yarn test
          env:
            SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          run: yarn test